### ISSUE TITLE
Add desktop file, icon, launch script

### ISSUE THREAD

**Issue by glixx** [mse-org/mselang#1]
linux_extra dir with:
mselang
mselang.desktop

image dir:
paint new icon.

**Comment by glixx** [comment]
Added linux_extra dir.

Needs to rename images from https://github.com/mse-org/mselang/tree/master/src/image into mselang* and to change color.

Blue is mseide.
Green is msei18n.

What color for mselang?

**Comment by fredvs** [comment]
Purple ?

![msegui_64](https://user-images.githubusercontent.com/3421249/54281788-cdb54580-459a-11e9-9905-592c52e23fed.png)
![msegui_48](https://user-images.githubusercontent.com/3421249/54281818-db6acb00-459a-11e9-9bfd-a58fe673f896.png)
![msegui_32](https://user-images.githubusercontent.com/3421249/54281827-df96e880-459a-11e9-9717-18a326d1fca4.png)
![msegui_24](https://user-images.githubusercontent.com/3421249/54281838-e58cc980-459a-11e9-8c83-ebb89d6a242c.png)

**Comment by fredvs** [comment]
Or Deep Purple?

![mselang_64](https://user-images.githubusercontent.com/3421249/54297116-77560000-45b6-11e9-97cb-656a3b7fd40d.png)
![mselang_48](https://user-images.githubusercontent.com/3421249/54297120-7a50f080-45b6-11e9-89d2-f8bddffa0b27.png)
![mselang_32](https://user-images.githubusercontent.com/3421249/54297154-9359a180-45b6-11e9-865e-76c943a03f40.png)
![mselang_24](https://user-images.githubusercontent.com/3421249/54297182-9fddfa00-45b6-11e9-8672-e7d3129fcc49.png)

**Comment by fredvs** [comment]
Or Red?

![edelweiss2red_64](https://user-images.githubusercontent.com/3421249/54297238-c308a980-45b6-11e9-9385-6b288c042b8c.png)
![edelweiss2red_48](https://user-images.githubusercontent.com/3421249/54297255-cb60e480-45b6-11e9-9d13-af8176630d5e.png)
![edelweiss2red_32](https://user-images.githubusercontent.com/3421249/54297271-d6b41000-45b6-11e9-95c0-608689535414.png)
![edelweiss2red_24](https://user-images.githubusercontent.com/3421249/54297282-dca9f100-45b6-11e9-8ec0-94e86355a511.png)

**Comment by glixx** [comment]
Purple is ok

**Comment by fredvs** [comment]
Thanks.
Done 25643d9

**Comment by glixx** [comment]
And svg too

**Comment by fredvs** [comment]
> And svg too

I do not have program to save as svg.

**Comment by glixx** [comment]
inkscape

**Comment by fredvs** [comment]
`$ sudo apt-get install inkscape`

Done.

**Comment by fredvs** [comment]
> And svg too

Done.

**Comment by glixx** [comment]
Purple is different. Needs export from svg to png.

**Comment by fredvs** [comment]
> Purple is different. Needs export from svg to png.

Done.

**Comment by glixx** [comment]
src/main.mfm was not updated.
64.png is low quality.

**Comment by fredvs** [comment]
> src/main.mfm was not updated.
> 64.png is low quality.

Done.

**Comment by glixx** [comment]
Your (gradients were not changed):
![Screenshot_20190314_031319](https://user-images.githubusercontent.com/2681872/54328850-807bb700-4620-11e9-8435-67366d8abf19.png)

My (gradients were changed):
![Screenshot_20190314_031357](https://user-images.githubusercontent.com/2681872/54328861-870a2e80-4620-11e9-8ae5-6924b743ed5f.png)

Using inkscape to create png from svg:
`inkscape -z -e mselang_64.png -w 64 -h 64 mselang.svg`

Sorry, but I changed icons.
I did not touch src/main.mfm.

**Comment by fredvs** [comment]
`inkscape -z -e mselang_64.png -w 64 -h 64 mselang.svg`

Wow. (Sorry but I am not (yet) the best inskape-guru, I did the conversion with Gimp.)

I did update the icons of forms with your icons.

Thanks!

**Comment by glixx** [comment]
Gimp always saves low quality especially low resolutions pictures if to compare with PhotoShop.
