### ISSUE TITLE
Development stalled?

### ISSUE THREAD

**Issue by 3oheicrw** [mse-org/mselang#4]
No new commits since 2019? So this LLVM based Pascal compiler is dead?

**Comment by fredvs** [comment]
Hello.

MSElang is not dead but it needs support.

Everybody is welcome to continue the project.

**Comment by 3oheicrw** [comment]
> Hello.
> 
> MSElang is not dead but it needs support.
> 
> Everybody is welcome to continue the project.

This is just another way to say the project is dead. Thanks for this information anyway.
